before_install:
  - apt-get update -y
  - apt-get install -y bison flex make automake autoconf libtool pkg-config

install:
  - echo "Installing dependencies"

jdk:
  - openjdk17

android:
  components:
    - platform-tools
    - build-tools-34.0.0
    - android-34
    - cmake-3.22.1
    - ndk-26.1.10909125

script:
  - ./gradlew assembleRelease