name: Build arm64 NDK library

on:
  push:
    branches:
      - xlorie

jobs:
  build:
    name: "Build arm64 library"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: xlorie
        submodules: recursive
        fetch-depth: 1

    - name: Java setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build arm64 library
      run: |
        ./gradlew externalNativeBuildRelease -Pandroid.abis=arm64-v8a -PcmakeBuildType=MinSizeRel
        find app/build -name "libXlorie.so" -path "*/arm64-v8a/*" -exec strip --strip-debug {} \;

    - name: List build directories for debugging
      run: |
        echo "Listing build directories:"
        find app/build -name "*.so" -type f | head -20
        echo "Full cxx directory structure:"
        find app/build/intermediates/cxx -type d 2>/dev/null || echo "cxx directory not found"
        echo "Release directory contents:"
        ls -la app/build/intermediates/cxx/Release/ 2>/dev/null || echo "Release directory not found"

    - name: Store arm64 library
      uses: actions/upload-artifact@v4
      with:
        name: libXlorie-arm64
        path: app/build/intermediates/cxx/RelWithDebInfo/*/obj/arm64-v8a/libXlorie.so