name: Build Android NDK Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

env:
  ANDROID_NDK_VERSION: "25.2.9519653"
  CMAKE_VERSION: "3.22.1"
  BUILD_TYPE: "Release"

jobs:
  build-android-ndk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Java setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y patch bison make ninja-build
    
    - name: Download Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: ${{ env.CMAKE_VERSION }}
    
    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ../app/src/main/cpp \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk/${{ env.ANDROID_NDK_VERSION }}/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-21 \
          -DANDROID_STL=c++_shared \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -GNinja
    
    - name: Build the library
      run: |
        cd build
        cmake --build . --config ${{ env.BUILD_TYPE }} --verbose
    
    - name: List built artifacts
      run: |
        find build -name "*.so" -o -name "*.a" | xargs ls -la
    
    - name: Archive built libraries
      uses: actions/upload-artifact@v3
      with:
        name: android-libraries
        path: |
          build/**/*.so
          build/**/*.a