name: Build arm64 NDK library

on:
  push:
    branches:
      - xlorie

jobs:
  build:
    name: "Build arm64 library"
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: xlorie
        submodules: recursive
        fetch-depth: 1

    - name: Java setup
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build arm64 library
      run: ./gradlew externalNativeBuildRelease -Pandroid.abis=arm64-v8a

    - name: Store arm64 library
      uses: actions/upload-artifact@v4
      with:
        name: libXlorie-arm64
        path: app/build/intermediates/cxx/Release/*/obj/arm64-v8a/libXlorie.so